Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 100

Layout/MultilineMethodCallIndentation:
  Enabled: False

Style/TrailingCommaInLiteral:
  Enabled: False
