version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env.docker
    networks:
      - private
    depends_on:
      - redis

  redis:
    image: redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env.docker
    networks:
      - private
    depends_on:
      - redis

  #db:
  #  image: postgres
  #  networks:
  #    - private

  #loadbalancer:
  #  image: 'dockercloud/haproxy'
  #  links:
  #    - web
  #  ports:
  #    - '80:80'
  #    - '443:443'
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  networks:
  #    - public
  #    - private

networks:
  public:
  private:
