version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379
  resque_web:
    image: resque_web
    build:
      context: .
      dockerfile: worker/Dockerfile.resque_web
  ellie_web:
    image: ellie_web
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file: .env
    ports:
      - 9292:9292
  ellie_worker:
    image: ellie_worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file: .env

