development:
  adapter: postgresql
  encoding: unicode
  database: ellieactive_development
  pool: 2
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: ellieactive_test
  pool: 2
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 2
  url: 'postgres://ellie_dev_team:H4rdC4s3!99@ellie-production-v2.cabmxdxjziky.us-east-1.rds.amazonaws.com:5432/ellie_production'